### ISSUE TITLE
Client Hints + initial state Adaptive Loading Hooks

### ISSUE THREAD

**Issue by addyosmani** [GoogleChromeLabs/adaptive-loading#102]
Now that https://github.com/GoogleChromeLabs/react-adaptive-hooks support setting initial values (e.g `initialEffectiveConnectionType`), I think there would be value in showing how Client Hints can provide an initial value on the server and this can then be updated, if necessary, on the client-side via the JS APIs exposed in Hooks.

**Stack requirement:**
We should build an app that uses Next.js as it has to keep SSR in mind and would be a good "stress test" this all works together. 

Signal wise, I think it's fine to rely on Network and Device Memory. We would want this demo to be responsive and render cleanly on both mobile and desktop. Output should have at least a 90/100 on Lighthouse for performance.

**What are we building?**
A clean, nice-looking TV show browser. TMDB's API provides the data to allow us to build this. It's very similar to our existing TMDB client built using CRA, except will focus on shows rather than movies. There are a few existing Next.js open-source apps we could look to for reference here.

**Reference**
https://topheman-movie-browser.herokuapp.com/ is from this year and is open-source https://github.com/topheman/nextjs-movie-browser. 

https://github.com/timneutkens/next-episode is a Next.js TV show app that might be a good fit here. It's 2 years old so likely requires an upgrade to get it working with the latest version of Next.

I really like how next-episode looks. It would be good to evaluate if it makes more sense to fork it and update or try improving the design of nextjs-movie-browser. We could also choose to write something from scratch if there are too many "extras" in either implementation.

cc @anton-karlovskiy

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I'd like to play around with nextjs-movie-browser and next-episode shortly.
If you've got an idea, please update me then I'll switch to your idea immediately. :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

We can keep track of the progress on this Glitch.
## Glitch Source

* [Link to Glitch App](https://anton-karlovskiy-next-show-adaptive-loading.glitch.me/)
* [Link to Project on Glitch](https://glitch.com/~anton-karlovskiy-next-show-adaptive-loading/)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I met some challenge when using [react-adaptive-hooks](https://github.com/GoogleChromeLabs/react-adaptive-hooks) in Next.js project.

![react-hooks-challenge](https://user-images.githubusercontent.com/49653735/70555175-98706f00-1b8f-11ea-88b5-e1966f43cba9.PNG)
![react-hooks-challenge-import-hooks](https://user-images.githubusercontent.com/49653735/70555181-99a19c00-1b8f-11ea-8f3c-633928212f8b.PNG)
![react-hooks-challenge-inside-hooks](https://user-images.githubusercontent.com/49653735/70555186-9b6b5f80-1b8f-11ea-9e65-1c52585603d2.PNG)

Just importing react adaptive hooks in next.js page throws an error.
```
import { useMemoryStatus } from 'react-adaptive-hooks/memory';
import { useNetworkStatus } from 'react-adaptive-hooks/network';
```

I think the cause of this issue is because ES6 features like `import` and `export` from our `react-adaptive-hooks` package are not properly transpiled in Next.js.
Re:
https://stackoverflow.com/questions/37634198/node-error-syntaxerror-unexpected-token-import

We could resolve this issue by customizing babel configuration for Next.js so that it can transpile our react-adaptive-hooks package in node_modules.

I fixed this issue with [next-transpile-modules](https://github.com/martpie/next-transpile-modules).

I wonder if we should publish the transpiled package to npm.
When users are using custom server for Next.js project, they could meet this issue in spite of installing `next-transpile-modules` so they might have to customize babel to transpile custom server.

Re:
https://github.com/zeit/next.js/issues/6273

**Comment by addyosmani** [comment]
@anton-karlovskiy Thank you for raising this concern. Can I confirm if you are running into this issue when using the UMD version of the package as well? We recently added a bundled version that doesn't use raw ESM that could be pulled in e.g see https://unpkg.com/react-adaptive-hooks@0.0.8/dist/index.umd.js.

Are you still experiencing those issues when importing the whole package?

**Comment by addyosmani** [comment]
Any updates on whether the UMD build helped here, @anton-karlovskiy? :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Sorry for being late. Let me update you shortly. :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I tested with UMD build. It's working well.

This is ESM build usage
```
import { useMemoryStatus } from 'react-adaptive-hooks/memory';
import { useNetworkStatus } from 'react-adaptive-hooks/network';
```

This is UMD build usage
```
import { useNetworkStatus, useMemoryStatus } from 'react-adaptive-hooks/dist/index.umd.js';
```

For using ESM build in Next.js, we need to transpile this package because server side does not understand ES6 module features like `import` and `export`.

Or we can use UMD build as a fallback.

Which one shall we use?
I wonder if using UMD is a bit more overheaded than path import with ESM build.

**Comment by addyosmani** [comment]
Let's try getting the ESM build working. Official Node support for ESM is finally in a good place, but given how recent this we may have to rely on workarounds. We can use the UMD build in case we get stuck.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

We are not stuck as we found a workaround like transpiling react-adaptive-hooks package with the help of [next-transpile-modules](https://github.com/martpie/next-transpile-modules) or babel configuration.

Let me proceed with ESM and that workaround.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

The TV show app with ESM build of react-adptive-hooks and transpiling of that package won't work on Glitch. But it's working on Now service hosting and Firebase hosting too.

The app just with UMD build is working well on Glitch.
* [Link to Glitch App](https://anton-karlovskiy-next-show-adaptive-loading.glitch.me/)
* [Link to Project on Glitch](https://glitch.com/~anton-karlovskiy-next-show-adaptive-loading/)

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Do you think we can close this issue?

**Comment by addyosmani** [comment]
Yep!
